apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prod
spec:
  encryptedData:
    password: AgCXzprblsdO7jtPusGfIPk/Ldn4TmVwqS5ycgzGoyORo+VCznO/Sbx2wZQ30Pno0F+cATAZUZk16uDhVhP9Fff/VtYgxwn9TJPQ9tH8NdSchlWe+CmtKEUB6suIbQxidb5GSRTWY2vZA960sQ70ZJ/l7Pa4tpoJYykaiiTeaFUXWbLcDssKAI4v5j+xK6JV2oNMwttUdRb72AqQobEpX+x46CudBafFLeaFSVHZ1PGb7/pWkpti9wmuzwdg1UdSuj9SEf7lP4l6oj78xrzN0CXpW6qzB7QzLuICYQBXyWvEW4klLvw9A2ABAfBQO2mDtRBwx22QVZwHJ2ftktdB+cczVE1fQqnY2F1Nfvs2+Ka8aIbMePS5F/2wywxNpJCsJp97qxO7ke9c2hNCOzfXtEfg3UbPy7j63LEeOunWB5pnMPjkbLWX0kymKAW/UYHFyKia+2jea7jWjyJRjPbRWW+Yp4RXozpxs81Dn7KZXs5WBpu9CbLGMtIF9Jd/uJqRKSqixhgdZmT854r39m1dPj04M1SFQj36Xp3bAY8slgVFih2mtdqp18kvwfq3QasXWeky7Von7E+D6jeqVJAV+SwjZIHDk/iyAT65dtJ9qHrVoFo5vqkl+oip63FVOOrmO0gHWqH0yVKyZgFOClfjO+fOYuIW+xWnDYtJ+8Ic37HHHS8kTps6zRzlv6CXBcxyQY7gQ/2NcQ==
    user: AgCu9CBOS0omBVwHx/m3W4B6hp3ytVT3tNKzudKyfHHN5Pr5KIMcXxiJxY5I3+v2Ob+ikcNyLYxrx9/FndbHrDfdWNP0NoPJR5g/1aQKrD+bmYbGB/oBXLDMMfQC6Scy7gt8VJOMfMhk8wUyjc599rOVTfpTgIes6FE/SLZWoGMt4b0AhSmTZi7iRK/Wc2N6yuwPbM01rLX+6Ldk9eW3/W1rV4/SZN5Ro92msomoSqTHAUEZrQrQKtiY3uqBXvQxC4zenDQx511O5vF7hYkhnYX4MHD2MLbYTXM5NvSfNBfadi1ux6ZZcgONpNFfu+aidDUaaElxALiLtWAaukMjSP/VGknack6u7ZTxcPqIqXwm+JagNKXNR8veMjIXPY96Ux6Csg4YZyuwczVZljjeGFkGf7bWeJwxMhaY5MulB2elE2Mdk/pP5Enlx19zeVaGKpFjyOcjxlmtSGbc8vhw1m254EQ4RuPlFxrKn9Y7Da7CLO3+vnZr8WQzu3YISoq5uOny97SE/9F2DYn3ou08ZQxRNYY3+0ztko6E8bSgpcnDXoQRA9EOIsJASfIVNPZa0k6Ftiy+b2V+8GbcgWkb6n3anlBWnWKP9lh+U08HrCtLIHCx9u7TfW8Yjp0G45NncRu0FT6HQR0mTl84qXLsqA3axXm6E3Ti+pI7sAhpKvxwz90NXssUdEycMXLLvI47BqHJSeRBNQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: prod

