apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: nginx-ingress
  chart:
    git: git@github.com:kubernetes/ingress-nginx
    ref: master
    path: charts/ingress-nginx
  values:
    controller:
      service:
        type: LoadBalancer
